important_class_dict = {
    "CW_D": ["T_signal"],
    "CW_U": ["T_signal"],
    "PW_D": ["T_signal"],
    "PW_U": ["T_signal"],
    "CW_PW_U": ["T_signal"],
    "CW_PW_D": ["T_signal"],
    "CW_U_D": ["T_signal"],
    "PW_U_D": ["T_signal"],
    "CW_PW_U_D": ["T_signal"],
    "simple_D": ["T_signal"],
    "EA": ["T_signal",],
    "TDI": ["T_signal"],
    "vein": ["T_signal"],
    "MR CW": ["T_signal"],
    "PV(RVOT) PW": ["T_signal"],
    "AV(LVOT) PW": ["T_signal"],
    "TR CW": ["T_signal"],
    "MV(MS) CW": ["T_signal"],
    "AV(AS) CW": ["T_signal"],
    "all": ["T_signal"],
}
